#!/bin/bash

if [ "$USER" != "root" ]; then
	echo "Must be run as root or via sudo"
	exit
fi

if [ -z $1 ]; then
	echo "Specify chroot location"
	exit
fi

if [ ! -e $1 ]; then
	echo "Mount point \"$1\" not found"
	exit
fi

if [ "$1" == "/" ]; then
	echo "Chroot location CANNOT be root"
	exit
fi

for f in dev sys proc run; do
	if [ ! -e $1/$f ]; then
		echo "Mount point \"$1/$f\" not found. Is this a chroot?"
		exit
	fi
done

mount -v -t devtmpfs /dev $1/dev
mount -v -t devpts /dev/pts $1/dev/pts
mount -v -t sysfs /sys $1/sys
mount -v -t proc /proc $1/proc
mount -v -t tmpfs /run $1/run
