#!/bin/bash

if [ "$USER" != "root" ]; then
	echo "Must be run as root or via sudo"
	exit
fi

if [ -z $1 ]; then
	echo "Specify chroot location"
	exit
fi

if [ ! -e $1 ]; then
	echo "Mount point \"$1\" not found"
	exit
fi

if [ "$1" == "/" ]; then
	echo "Chroot location CANNOT be root"
	exit
fi

for f in dev sys proc run; do
	if [ ! -e $1/$f ]; then
		echo "Mount point \"$1/$f\" not found. Is this a chroot?"
		exit
	fi
done

umount -v $1/dev/pts
umount -v $1/dev
umount -v $1/sys
umount -v $1/proc
umount -v $1/run
